### ISSUE TITLE
关于使用文档及项目功能的优化建议

### ISSUE THREAD

**Issue by Rlxzmdd** [Cooooldwind/163ListDownloader_NexT#4]
最近在寻找用于批量下载网易云音乐歌单的脚本，遂遇到一个本项目，但该项目的文档和代码结构不够友好，导致上手难度较高。主要问题包括：
1. README.md 无法提供任何有效信息。
包括但不限于参数说明，文件目录结构说明。
2. 代码命令不规范。
当我首次使用应用，却无法理解参数有什么用时。我第一时间打开了ncmlistdownloader/__init__.py。但就在打开一瞬间，我关掉了。aa、bb、cc变量让我摸不着头脑。遂第一时间关闭该文件，去其他文件寻找参数说明。
建议所有者使用gpt4o模型对变量命名进行统一整理并生成简要注释。
3. 发行页中的项目是老版本。
项目发行页提供的仍是旧版本代码，未能反映当前代码的最新变化。

其次是关于功能建议方面有几点个人想法：
1. 可以在第一次运行结束后，自动生成配置文档。保存用户扫码得到的令牌，以及用户输入的除歌单id以外各类参数。从而减少重复的输入过程。
2. 歌曲下载过程中有几点显著问题：
 - 扫码获取cookies也无法下载vip音乐。这或许跟两个月未更新有关系。
 - 若选择无损音质，部份可下载音源也会出现只有1kb大小的情况。当切换到次一等级时，可下载对应质量音源。可在此添加一个循环判断，当文件大小为1kb，下载次一等级音源自动填补。也可以直接下载ncm音源，再调用解锁工具进行解锁。
3. 每次下载歌曲根据目标文件夹已有歌曲，进行增长下载。将方便自建音乐库用户，实时订阅自己网易云歌单。

希望项目维护者参考以上建议，并预祝开发顺利；）

**Comment by Cooooldwind** [comment]
感谢您对本项目的支持！

我近期正在重构这个项目，您可以关注 https://github.com/Cooooldwind/class163 。它是一个python库，整合了较多功能。同时那个项目也使用了包括豆包，Chat GPT在内的多个AI工具开发。

这是一个较年久失修的软件了，我将对您提出的问题进行回复。

1. 前三个问题，很抱歉，我可能不会实行。当 NeteaseDownloader 开发好（同样是我的项目，请前往主页查看）之后，谁还会用这个东西呢？毕竟它可是利用PySide6和qfluentwidgets开发的。
2. 关于下载：因为走的是官方接口，下载高音质音频有两个条件：必须是登录用户，必须充黑胶VIP/SVIP。如果是付费歌曲，还得先买断才能使用。经过测试，朋友领的两天/五天/七天黑胶可以正常使用，但是看广告领的黑胶无法使用。所以还是请自己氪金吧。pdd上有几十块钱的一年黑胶挺管用的，一周也就3～4块钱。毕竟都用上flac格式的无损了，花他一瓶可乐钱也无妨了吧，就当支持正版了。当然，身边有朋友能给你2天试用是最好的。但是试用只能一个月一个朋友拿一张（我记得是的）。
3. 关于音源：我最近在class163研究让某些提供音源的API开发者使用脚本重定义其中某些类的函数，从而达到修改音乐下载链接的效果。当然还在极其极其早期的开发阶段（准确来说，让AI帮我生成了一个脚本）。敬请期待。

感谢您的等待和支持。因为我现在还是高中在校学生，无法及时回复，敬请谅解。同时能看到您如此认真的提交issues我很感动。再次感谢。
